---
name: CMake

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should
    # work equally well on Windows or Mac.  You can convert this to a matrix
    # build if you need cross-platform coverage.
    # yamllint disable-line rule:line-length
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
          - os: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Fix Checkout
        run: |
          git fetch --force --tags

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate
        # build directory. We'll use this as our working directory for all
        # subsequent commands
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment
        # variable access regardless of the host operating system
        shell: bash
        working-directory: ${{github.workspace}}/build
        # Note the current convention is to use the -S and -B options here to
        # specify source and build directories, but this is only available
        # with CMake 3.13 and higher. The CMake binaries on the Github Actions
        # machines are (as of this writing) 3.12
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        # Execute the build.  You can specify a specific target
        # with "--target <NAME>"
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more
        # detail
        run: ctest -C $BUILD_TYPE

      - if: ${{ failure() }}
        name: Upload test data
        uses: actions/upload-artifact@v2
        with:
          name: tests-out
          path: tests

      - if: ${{ failure() }}
        name: Upload cmake test output
        uses: actions/upload-artifact@v2
        with:
          name: tests-out
          path: build/Testing
